change yml files

diff --git a/.github/workflows/Validate-deploy.yml b/.github/workflows/Validate-deploy.yml
--- a/.github/workflows/Validate-deploy.yml
+++ b/.github/workflows/Validate-deploy.yml
@@ -21,22 +21,25 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: 3.13.2
-    - name: Fetch base and head branches/commits
-      run: |
-        git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
-        git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
-        
+
     - name: Run generateXML.py
+      id: generate-xml
       run: |
         python generateXML.py \
           --base_branch ${{ github.event.pull_request.base.ref }} \
           --compare_branch ${{ github.event.pull_request.head.ref }}
+        if [ ! -f "package.xml" ]; then
+          echo "Package XML not found."
+          exit 1
+        fi
 
     - name: Decode JWT key
+      if: ${{ steps.generate-xml.outcome == 'success' }}
       run: |
         echo "${{ secrets.SF_JWT_SECRET }}" > server.key
 
     - name: Authenticate with Salesforce (sf CLI)
+      if: ${{ steps.generate-xml.outcome == 'success' }}
       run: |
         sf org login jwt \
           --client-id ${{ secrets.SF_CONSUMER_KEY }} \
@@ -47,6 +50,7 @@ jobs:
           --set-default
 
     - name: Validate Deployment using package.xml
+      if: ${{ steps.generate-xml.outcome == 'success' }}
       run: |
         sf project deploy validate \
           --manifest package.xml \
@@ -54,3 +58,4 @@ jobs:
           --test-level RunLocalTests \
           --wait 10 \
           --verbose
+
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,17 +28,27 @@ jobs:
             git fetch origin ${{ github.sha }}:${{ github.sha }}
 
       - name: Run generateXML.py
+        id: generate-xml
         run: |
           python generateXML.py --base_commit ${{ github.event.before }} --head_commit ${{ github.sha }}
+          if [ ! -f "package.xml" ]; then
+            echo "Package XML not found."
+            exit 1
+          fi
+          if [ -f "destructiveChanges.xml" ]; then
+            echo "destructiveChanges=true" >> $GITHUB_ENV
+          else
+            echo "destructiveChanges=false" >> $GITHUB_ENV
 
       - name: Decode JWT key
+        if: ${{ steps.generate-xml.outcome == 'success' }}
         run: |
           echo "${{ secrets.SF_JWT_SECRET }}" > server.key
 
       - name: Authenticate with Salesforce (sf CLI)
+        if: ${{ steps.generate-xml.outcome == 'success' }}
         run: |
           sf org login jwt \
-
             --client-id ${{ secrets.SF_CONSUMERUAT_KEY }} \
             --jwt-key-file server.key \
             --username ${{ secrets.SF_USERNAME_UAT }} \
@@ -47,6 +57,7 @@ jobs:
             --set-default
 
       - name: Deploy Metadata to Salesforce
+        if: ${{ steps.generate-xml.outcome == 'success' }}
         run: |
           sf deploy metadata \
             --manifest package.xml \
@@ -56,7 +67,7 @@ jobs:
             --verbose
 
       - name: Deploy Destructive Changes (if present)
-        if: ${{ hashFiles('destructiveChanges.xml') != '' }}
+        if: ${{ env.destructiveChanges == 'true' && steps.generate-xml.outcome == 'success' }}
         run: |
           sf deploy metadata \
             --manifest package.xml \
